In [1]:
import numpy as np
from sklearn.decomposition import PCA, TruncatedSVD
X = np.array([[-1, -1, 0], [-2, -1, 4], [-3, -2, 1], [1, 1, 2], [2, 1, 0], [3, 2, 1]])
pca = PCA(n_components=2, whiten=True)
pca.fit(X)

print(pca.explained_variance_ratio_) 
print pca.components_

[ 0.79801395  0.20087926]
[[ 0.82538528  0.52692826 -0.20269618]
 [ 0.08508058  0.23883512  0.96732574]]


In [2]:
from scipy import linalg
n_samples, n_features = X.shape
U, S, V = linalg.svd(np.cov(X.transpose()), full_matrices=False)
explained_variance_ = (S ** 2) / n_samples
explained_variance_ratio_ = (explained_variance_ / explained_variance_.sum())
components_ = V

print explained_variance_ratio_ , '\n'
print components_, '\n'
print explained_variance_

[  9.40409193e-01   5.95889981e-02   1.80896615e-06] 

[[-0.82538528 -0.52692826  0.20269618]
 [-0.08508058 -0.23883512 -0.96732574]
 [ 0.55812224 -0.81566193  0.15229963]] 

[  1.11873864e+01   7.08888377e-01   2.15199973e-05]


In [3]:
eigenvalues, eigenvectors = np.linalg.eig(np.cov(X.transpose()))
print eigenvalues, '\n'
print eigenvalues / eigenvalues.sum(), '\n'
print eigenvectors

[ 8.19294321  0.0113631   2.06236036] 

[ 0.79801395  0.0011068   0.20087926] 

[[ 0.82538528  0.55812224  0.08508058]
 [ 0.52692826 -0.81566193  0.23883512]
 [-0.20269618  0.15229963  0.96732574]]


In [4]:
#svd = TruncatedSVD(n_components=2, algorithm='arpack').fit(np.cov(X.transpose()))
svd = TruncatedSVD(n_components=2, algorithm='arpack').fit(X)
print svd.explained_variance_ratio_
print svd.components_

[ 0.79211518  0.2055658 ]
[[-0.80642175 -0.51033815  0.29872887]
 [ 0.20899656  0.22659823  0.95130105]]


In [5]:
import time

In [6]:
%timeit U, S, V = linalg.svd(X, full_matrices=False)

1000 loops, best of 3: 108 µs per loop


In [7]:
%timeit eigenvalues, eigenvectors = np.linalg.eig(np.cov(X.transpose()))

1000 loops, best of 3: 111 µs per loop
